version: '{build}'
branches:
  only:
    - main
    - /^golded-.*/
environment:
   matrix:
    - generator: Visual Studio 16 2019 
      pf: "msvc2019"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
install:
  - cmd: copy golded3\mygolded.__h golded3\mygolded.h
build_script:
  - cmd: mkdir build && cd build && cmake --version
  - cmd: cmake .. -G "%GENERATOR%" 
  - cmd: cmake --build . -- /P:Configuration=Release
  - cmd: cpack
  - ps:  gci *.7z | %{ rename-item –path $_.Fullname –Newname ( $_.basename +"-"+$Env:pf+$_.extension) }
artifacts:
  - path: build\*.7z
    name: dist