##  -------------------------------------------------------------------
##  The Goldware Library. Copyright (C) Odinn Sorensen and Golded+ team
##  -------------------------------------------------------------------
## GCUI: Golded+ Character-oriented User Interface library.
##  -------------------------------------------------------------------
# $Id$
# Build library using GNU make and CNU C++ compuler.

TOP=../..
TARGET=gcui
INCS=-I$(TOP)/goldlib -I$(TOP)/goldlib/gcui -I$(TOP)/goldlib/gall

include $(TOP)/Config.def
include $(TOP)/GNUmakef.inc
include $(TOP)/GNUmakef.lib
